[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crowdfunding = "G4qPXXjL3U2gYmAwEwzTkX1oKjwhPC14RuxZvjfSAPCU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
